# Generated by Django 6.0.6 on 2026-08-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง')], default='ชาย', max_length=5)),
                ('birthdate', models.DateField()),
                ('department', models.CharField(choices=[('ไอที', 'ไอที'), ('การเงิน', 'การเงิน'), ('ช่างซ่อม', 'ช่างซ่อม')], default='ไอที', max_length=50)),
                ('salary', models.IntegerField()),
                ('pics', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
