# Generated by Django 6.0.6 on 2026-09-15 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่องาน')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียดงาน')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('in_progress', 'กำลังทำ'), ('completed', 'เสร็จสิ้น')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('due_date', models.DateField(verbose_name='กำหนดส่ง')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='employeeapp.employee')),
            ],
        ),
    ]
