# Generated by Django 6.0.6 on 2026-09-15 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pics',
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='วันที่บันทึก'),
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_images/', verbose_name='รูปภาพพนักงาน'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='วันที่มอบหมาย'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='แผนก'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fname',
            field=models.CharField(max_length=100, verbose_name='ชื่อจริง'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง'), ('อื่นๆ', 'อื่นๆ')], default='ชาย', max_length=10, verbose_name='เพศ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lname',
            field=models.CharField(max_length=100, verbose_name='นามสกุล'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='เงินเดือน'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียดงาน'),
        ),
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='employeeapp.employee', verbose_name='ผู้รับผิดชอบงาน'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'รอดำเนินการ'), ('in_progress', 'กำลังดำเนินการ'), ('completed', 'เสร็จสิ้น')], default='pending', max_length=20, verbose_name='สถานะงาน'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='วันที่ลงเวลา')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='เวลาเข้างาน')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='เวลาออกงาน')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='ละติจูด (GPS)')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='ลองจิจูด (GPS)')),
                ('status', models.CharField(default='On Time', max_length=50, verbose_name='สถานะการเข้างาน')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employeeapp.employee', verbose_name='พนักงาน')),
            ],
        ),
    ]
