# Generated by Django 6.0.6 on 2026-09-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0003_remove_employee_birthdate_remove_employee_pics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='วัน/เดือน/ปีเกิด'),
        ),
    ]
