# Generated by Django 6.0.6 on 2026-09-15 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0004_employee_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('sick', 'ลาป่วย'), ('personal', 'ลากิจ'), ('annual', 'พักร้อน')], max_length=20, verbose_name='ประเภทการลา')),
                ('start_date', models.DateField(verbose_name='ตั้งแต่วันที่')),
                ('end_date', models.DateField(verbose_name='ถึงวันที่')),
                ('reason', models.TextField(verbose_name='เหตุผลการลา')),
                ('status', models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ไม่อนุมัติ')], default='pending', max_length=20, verbose_name='สถานะการอนุมัติ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ยื่นคำขอ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employeeapp.employee', verbose_name='พนักงาน')),
            ],
        ),
    ]
