# Generated by Django 6.0.6 on 2026-09-16 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0007_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('available', 'พร้อมใช้งาน'), ('borrowed', 'กำลังถูกยืม'), ('maintenance', 'ซ่อมบำรุง')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('borrowing', 'กำลังยืม'), ('returned', 'คืนแล้ว')], default='borrowing', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeapp.employee')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeapp.equipment')),
            ],
        ),
    ]
